/**
 * Design system tokens extracted from a website
 */
export interface DesignTokens {
	colors: ColorToken[];
	typography: TypographyToken[];
	spacing: SpacingToken[];
	components: ComponentPattern[];
	elevation?: ShadowToken[];
	shapes?: ShapeToken[];
}

export interface ColorToken {
	name?: string;
	value: string; // hex, rgb, hsl format
	frequency: number; // how many times this color appears
	usage?: string; // primary, secondary, background, text, etc.
}

export interface TypographyToken {
	fontFamily: string;
	fontSize?: string;
	fontWeight?: number | string;
	lineHeight?: string;
	letterSpacing?: string;
	frequency?: number;
	usage?: string; // heading, body, caption, etc.
}

export interface SpacingToken {
	value: string; // px or rem value
	frequency: number;
	usage?: string; // padding, margin, gap, etc.
}

export interface ShadowToken {
	value: string;
	frequency: number;
	elevation?: number; // shadow level
}

export interface ShapeToken {
	borderRadius: string;
	frequency: number;
	usage?: string; // buttons, cards, etc.
}

export interface ComponentPattern {
	name: string;
	description?: string;
	colors?: string[];
	typography?: string[];
	spacing?: string[];
	borderRadius?: string;
}

export interface ExtractionResult {
	url: string;
	timestamp: string;
	tokens: DesignTokens;
	designPhilosophy?: string; // Generated by LLM
	componentGuidance?: string; // Generated by LLM
	dosAndDonts?: string; // Generated by LLM
}

export interface FormattedOutput {
	designMd: string;
	tailwind: string;
	cssVars: string;
	dtcg: object;
}
